name: Build binary packages

on:
  pull_request:
    branches:
      - "*"
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies for building
        run: |
          python -m pip install -U pip hatch uv
          hatch env create packaging
      - name: Build linux binary package
        run: hatch run packaging:build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: snow-${{ matrix.os }}
          path: |
            dist/
            build/
